; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Falcon Programmer"
#define MyAppPublisher "Simon O'Rorke"
#define MyAppURL "https://github.com/SimonORorke/FalconProgrammer"
#define MyAppExeName "FalconProgrammer.exe"

; Parse version from FalconProgrammer.csproj (<Version>x.y.z.w</Version>)
#define FileHandle
#define FileLine
#define RawVersion ""
#define OpenTag "<Version>"
#define CloseTag "</Version>"
#define StartPos
#define EndPos
#define CsprojPath SourcePath + "\..\..\FalconProgrammer\FalconProgrammer.csproj"

#for {FileHandle = FileOpen(CsprojPath); FileHandle && !FileEof(FileHandle); ""} \
  FileLine = FileRead(FileHandle), \
  (Pos("<!--", FileLine) == 0 && Pos(OpenTag, FileLine) > 0 && Pos(CloseTag, FileLine) > Pos(OpenTag, FileLine)) ? ( \
    StartPos = Pos(OpenTag, FileLine) + Len(OpenTag), \
    EndPos = Pos(CloseTag, FileLine), \
    RawVersion = Trim(Copy(FileLine, StartPos, EndPos - StartPos)), \
    FileClose(FileHandle), \
    FileHandle = 0 \
  ) : 0

#if FileHandle
  #expr FileClose(FileHandle)
#endif

#if RawVersion == ""
  #error Could not find <Version> in FalconProgrammer.csproj
#endif

; Omit the 4th part if zero (e.g. 1.2.0.0 -> 1.2.0)
#define Dot1 Pos(".", RawVersion)
#define Dot2 (Dot1 && Pos(".", Copy(RawVersion, Dot1 + 1, Len(RawVersion)))) ? Pos(".", Copy(RawVersion, Dot1 + 1, Len(RawVersion))) + Dot1 : 0
#define Dot3 (Dot2 && Pos(".", Copy(RawVersion, Dot2 + 1, Len(RawVersion)))) ? Pos(".", Copy(RawVersion, Dot2 + 1, Len(RawVersion))) + Dot2 : 0
#define Dot4 (Dot3 && Pos(".", Copy(RawVersion, Dot3 + 1, Len(RawVersion)))) ? Pos(".", Copy(RawVersion, Dot3 + 1, Len(RawVersion))) + Dot3 : 0

#if Dot3 && !Dot4 && Copy(RawVersion, Dot3 + 1, Len(RawVersion)) == "0"
  #define MyAppVersion Copy(RawVersion, 1, Dot3 - 1)
#else
  #define MyAppVersion RawVersion
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{40422C03-FF77-42B3-B1D8-D11CB91F1C19}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=..\..\LICENCE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=.\
OutputBaseFilename=FalconProgrammer{#MyAppVersion}x64
VersionInfoVersion={#MyAppVersion}
SetupIconFile=..\..\FalconProgrammer\Assets\falcon_svg_repo_com_512_512.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\FalconProgrammer\bin\x64\Release\net10.0\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\FalconProgrammer\bin\x64\Release\net10.0\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "*.pdb,runtimes\linux*,runtimes\osx*,runtimes\win-x86*,runtimes\win-arm64*"
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

